import { useState } from 'react'
import clsx from 'clsx'
import { useSiftStore } from '../store'

export default function AiPanel(): React.JSX.Element {
  const aiSuggestion = useSiftStore((s) => s.aiSuggestion)
  const isLoadingAi = useSiftStore((s) => s.isLoadingAi)
  const runAiSuggestion = useSiftStore((s) => s.runAiSuggestion)
  const hasApiKey = useSiftStore((s) => s.hasApiKey)
  const hasClaudeCli = useSiftStore((s) => s.hasClaudeCli)
  const setSettingsOpen = useSiftStore((s) => s.setSettingsOpen)
  const aiChat = useSiftStore((s) => s.aiChat)
  const isAskingAi = useSiftStore((s) => s.isAskingAi)
  const askAi = useSiftStore((s) => s.askAi)
  const summary = useSiftStore((s) => s.summary)
  const [question, setQuestion] = useState('')

  const canAsk = hasApiKey || hasClaudeCli
  const canAskNow = canAsk && !!summary

  const submitQuestion = (): void => {
    if (!question.trim() || isAskingAi || !canAskNow) return
    askAi(question)
    setQuestion('')
  }

  return (
    <div className="rounded-xl border border-[var(--sift-border)] bg-[var(--sift-surface)] p-4">
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <div className="size-6 rounded-md bg-[var(--sift-accent-soft)] flex items-center justify-center">
            <span className="text-[var(--sift-accent)] text-xs">✦</span>
          </div>
          <h3 className="font-medium text-[14px]">AI recommendations</h3>
        </div>
        {!aiSuggestion && (
          <button
            onClick={runAiSuggestion}
            disabled={isLoadingAi}
            className="text-[12.5px] font-medium text-[var(--sift-accent)] hover:underline disabled:opacity-50"
          >
            {isLoadingAi ? 'Thinking…' : 'Analyze'}
          </button>
        )}
      </div>

      {!aiSuggestion && !isLoadingAi && (
        <p className="text-[12.5px] text-[var(--sift-text-muted)]">
          {hasApiKey ? (
            'Claude API key set — click Analyze for tailored guidance.'
          ) : hasClaudeCli ? (
            'Using your local Claude Code CLI — no API key needed. Click Analyze for tailored guidance.'
          ) : (
            <>
              No Claude API key set and no local Claude Code CLI found —{' '}
              <button onClick={() => setSettingsOpen(true)} className="text-[var(--sift-accent)] hover:underline">
                add a key in Settings
              </button>{' '}
              or install Claude Code, or run local heuristics now.
            </>
          )}
        </p>
      )}

      {aiSuggestion && (
        <div className="space-y-3">
          {aiSuggestion.source === 'claude' ? (
            <p className="text-[11px] text-[var(--sift-accent)]">✦ Generated by Claude</p>
          ) : aiSuggestion.source === 'claude-cli' ? (
            <p className="text-[11px] text-[var(--sift-accent)]">✦ Generated via your local Claude CLI</p>
          ) : aiSuggestion.errorReason ? (
            <p className="text-[11px] text-[var(--sift-caution)]">
              Couldn&apos;t reach Claude ({aiSuggestion.errorReason}) — showing local analysis instead.{' '}
              <button onClick={() => setSettingsOpen(true)} className="underline">
                Check Settings
              </button>
            </p>
          ) : (
            <p className="text-[11px] text-[var(--sift-text-muted)]">
              Local analysis — no Claude key or CLI found.{' '}
              <button onClick={() => setSettingsOpen(true)} className="underline">
                Add one
              </button>
            </p>
          )}
          <p className="text-[13px] leading-relaxed text-[var(--sift-text)]/90">{aiSuggestion.summary}</p>
          <ul className="space-y-1.5">
            {aiSuggestion.recommendations.slice(0, 8).map((r) => (
              <li key={r.categoryId} className="flex items-start gap-2 text-[12.5px]">
                <span
                  className={clsx(
                    'mt-0.5 size-1.5 rounded-full shrink-0',
                    r.verdict === 'clear-it' && 'bg-[var(--sift-safe)]',
                    r.verdict === 'review-first' && 'bg-[var(--sift-caution)]',
                    r.verdict === 'keep' && 'bg-[var(--sift-text-muted)]'
                  )}
                />
                <span className="text-[var(--sift-text-muted)]">{r.reason}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="pt-3 mt-3 border-t border-[var(--sift-border)] space-y-2">
        {aiChat.map((turn, idx) => (
          <div key={idx} className="text-[12.5px] space-y-0.5">
            <p className="font-medium text-[var(--sift-text)]">{turn.question}</p>
            <p className="text-[var(--sift-text-muted)] leading-relaxed">{turn.answer}</p>
          </div>
        ))}
        {isAskingAi && <p className="text-[12px] text-[var(--sift-text-muted)]">Thinking…</p>}
        <div className="flex gap-1.5">
          <input
            type="text"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && submitQuestion()}
            disabled={!canAskNow}
            placeholder={
              canAsk
                ? summary
                  ? 'Ask about a specific file or category…'
                  : 'Scan first to ask questions…'
                : 'Add a Claude key or install Claude Code to ask questions…'
            }
            className="flex-1 rounded-lg border border-[var(--sift-border)] bg-[var(--sift-bg)] px-2.5 py-1.5 text-[12.5px] outline-none focus:border-[var(--sift-accent)] disabled:opacity-50"
          />
          {canAsk ? (
            <button
              onClick={submitQuestion}
              disabled={isAskingAi || !question.trim() || !canAskNow}
              className="rounded-lg bg-[var(--sift-accent-soft)] text-[var(--sift-accent)] px-3 py-1.5 text-[12px] font-medium disabled:opacity-40"
            >
              Ask
            </button>
          ) : (
            <button
              onClick={() => setSettingsOpen(true)}
              className="rounded-lg bg-[var(--sift-accent-soft)] text-[var(--sift-accent)] px-3 py-1.5 text-[12px] font-medium"
            >
              Settings
            </button>
          )}
        </div>
      </div>
    </div>
  )
}
